name: LEEP release

on:
  workflow_run:
    workflows: [LEEP tests]
    types: [completed]

jobs:
  build:

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
      # && startsWith(github.ref, 'refs/tags/v')

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu latest with py3.x
            os: ubuntu-latest
            python: "3.x"

    steps:
      - uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
            python-version: ${{ matrix.python }}

      - name: Install basic Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
                "setuptools>=64" \
                "setuptools-scm>=8" \
                wheel \
                twine
          which python
          python --version
          python -m pip --version
          python -m twine -h

      - name: Build
        run: |
          python3 -m build -v

      - name: List artifacts
        run: |
          ls dist/*

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "leep ${{ matrix.name }}"
          path: dist/*

      - name: Check wheels
        run: |
          python -m twine check dist/leep*.whl

      - name: Check source
        run: |
          python -m twine check dist/leep*.tar.*

      #- name: Upload package
      #  env:
      #    PYPI_REPOSITORY: pypi
      #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #  run: |
      #    python -m twine upload --repository ${PYPI_REPOSITORY} dist/*
