name: LEEP tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu latest with py3.x
            os: ubuntu-latest
            python: "3.x"

    steps:
      - uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
            python-version: ${{ matrix.python }}

      - name: Install basic Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest flake8
          which python
          python --version
          python -m pip --version
          python -m pytest --version
          python -m flake8 --version

      - name: Lint
        run: |
          find . -name "*.py" -exec flake8 {} +
        continue-on-error: true

      - name: Test
        run: |
          python -m pytest -v
